### PR TITLE
Update faq.json

### PR DESCRIPTION
**Pull request by nikobooth**
Major content update for FAQ page

### CODE REVIEW

**Comment by nikobooth** [comment]
@kengoy @thuongho Ruh-roh, I did a look through of the json file trying to find any silly errors (forgotten commas, open brackets) but didn't detect any. If one of you guys have time, could you take a look at why the checks are failing?

**Comment by kengoy** [comment]
@nikobooth There was unnecessary comma. I can fix it.

**Review by kengoy — APPROVED** [review]

**Comment by kengoy** [comment]
@nikobooth Great Job!

**Comment by nikobooth** [comment]
Thanks @kengoy !!!

**Pull request merged**
