### PR TITLE
Add side navigation to county guidlines

### PR DESCRIPTION
**Pull request by kbrdsk**
Issue #750 

This is an attempt at reusing the SideNavigationOverview component for the "County Info" page. 

The previous implementation used DOM ids for navigation but since those elements still exist on the page when switching tabs using refs to navigate and identify topics might work better.

The scroll length is also updated more frequently, this was originally to accommodate switching between counties in the tab but also seems to be useful when expanding questions in the FAQ. 

https://user-images.githubusercontent.com/52506986/103691804-a982df80-4f4b-11eb-8633-0b9dce3be3ad.mp4

### CODE REVIEW

**Comment by MosesSupposes** [comment]
We should merge this. Excellent job!

**Review by MosesSupposes — COMMENTED** [review]
Looks good. We should get one more review from @kengoy or @thuongho before we ship it.

**Comment by kbrdsk** [comment]
> Looks good. We should get one more review from @kengoy or @thuongho before we ship it.

Alright, thanks for taking a look at it.

**Review by kengoy — APPROVED** [review]
Looks good! Thank you for your contribution!

**Comment by kengoy** [comment]
@thuongho Can you also review this as well? If looks good, please merge it.

**Comment by thuongho** [comment]
@kbrdsk this is awesome! Love how you switched from id to refs. The code looks solid. I'd just like to add one little addition before the merge. Can you add `width: 100%` to `.SideNavigationOverview-Container .SideNav-MainContent-Scroll-Area` so that the content area expands the full width of the page? That will keep the info page at a constant width. :)

**Comment by kbrdsk** [comment]
@thuongho thanks! And yea totally. It doesn't seem to change anything for me though... The app has a max width of 1440, I think to match the background image of the header, could that be what you're referring to?

**Comment by thuongho** [comment]
@kbrdsk oops. Sorry I didn't mean the page, but making the `SideNav-MainContent-Scroll-Area` content area width 100% so that it stays consistent across different counties.

Screen Shot 2021-01-06 at 7 08 54 PM

Screen Shot 2021-01-06 at 7 09 10 PM

**Comment by kbrdsk** [comment]
@thuongho ohh I see, ok

**Comment by thuongho** [comment]
Sweet! Thanks @kbrdsk! LGTM.

**Pull request merged**
