### PR TITLE
Feature/issue106

### PR DESCRIPTION
**Pull request by kengoy**
@shaoevans @thuongho  

#106 The following remaining issues are fixed.

- Divide the chat into Confirmed Cases and Death Cases.
- Font is something strange for some reason. Top Navigation Bar font is strange too.
- Layout adjustment in each chart (font size of number, show date next to number)
- Last Updated at is wrong date

### CODE REVIEW

**Comment by thuongho** [comment]
@kengoy awesome job cleaning up design! Desktop looks really good. 

For the mobile side, should it be addressed on this PR as well or will it be in a separate ticket?

Screen Shot 2020-06-07 at 1 52 19 PM

The display looks slightly different from the wireframe. Also it is hard to tell what the numbers represent
IMG_5877

Maybe the info can be center aligned in this stats section?
IMG_5876

Also this dropdown
IMG_5875

**Comment by kengoy** [comment]
@thuongho Thanks for checking! I am aware of the mobile still needs to be adjusted. I will work on mobile fix as next step.

**Comment by thuongho** [comment]
@kengoy are you working on the fix on another ticket? If so, I can approve this PR for a merge. Otherwise I can leave it open. Let me know.

**Comment by kengoy** [comment]
@thuongho I will work on another ticket as it may take a bit more time. I believe it doesn't break the current mobile UI so can you approve and merge if looks good to you? I will create another PR for mobile once it is ready.

**Pull request merged**
