### PR TITLE
Revert "Feature/issue519"

### PR DESCRIPTION
**Pull request by thuongho**
Reverts sfbrigade/stop-covid19-sfbayarea#887

fyi @thomhammond, we never merge our own work. I left it up to @kengoy to take glance at it and pull the trigger.

### CODE REVIEW

**Comment by thuongho** [comment]
It is usually good to have a couple set of eyes on a PR. Depending on availability, in most cases one reviewer is ok.

**Comment by thomhammond** [comment]
> Reverts #887
> 
> fyi @thomhammond, we never merge our own work. I left it up to @kengoy to take glance at it and pull the trigger.

Oh no, sorry about that! I thought I saw a comment to go ahead from @kengoy but that makes total sense!

**Comment by thomhammond** [comment]
So, I'm not sure if I'm understanding this correctly or if something went wrong with the revert... When I go to https://panda.baybrigades.org/ the ShareWidget is live (and working correctly) but the deploy preview here is showing  the site without the ShareWidget. Basically the merge is still live and this merge would  actually revert? Just wanted to confirm this is expected behavior. Sorry for any confusion I created by going ahead with the merge :/

**Comment by thomhammond** [comment]
I did find an issue on the live site so I corrected it in a different branch since I'm not sure what is going on here. I will make a pr but basically I was using the current path to determine the styling on desktop. This was breaking when clicking the "Learn more about the project" button on the main page as this was adding a "/" to the path. I've changed this to use a prop to determine the page which is probably what I should have done from the beginning.

**Comment by thuongho** [comment]
> So, I'm not sure if I'm understanding this correctly or if something went wrong with the revert... When I go to https://panda.baybrigades.org/ the ShareWidget is live (and working correctly) but the deploy preview here is showing the site without the ShareWidget. Basically the merge is still live and this merge would actually revert? Just wanted to confirm this is expected behavior. Sorry for any confusion I created by going ahead with the merge :/

Yea basically since I didn't merge this revert, your PR merge still stands. It's ok, I'll just close this one and keep the merge as is.

**Pull request closed without merging**
