### PR TITLE
Show news for all bay area counties

### PR DESCRIPTION
**Pull request by Mr0grog**
~**Important:** this depends on sfbrigade/data-covid19-sfbayarea#81, which has to be merged first (otherwise the automatic updates will break).~

This adds news for each bay area county and switches from our custom format to [JSON Feed](https://jsonfeed.org/) (a standardized news feed format). This also means we have a separate file for each county. The data directory has switched from:

```
data/
  - data.json
  - faq.json
  - news.json
```

To:

```
data/
  - data.json
  - faq.json
  - news/
    - alameda.json
    - contra_costa.json
    - marin.json
    - napa.json
    - san_francisco.json
    - san_mateo.json
    - santa_clara.json
    - solano.json
    - sonoma.json
```

I’ve tried to break this up into reasonably separate steps, so it’s easy to merge only part of it if we want:
1. Switch from one news file to one news file per county.
2. Add news files for each county.
3. Change the format for each file from our old style to JSON Feed.

I’m fairly certain this doesn’t match the latest designs for the news page (I’m not totally up-to-date on that), but I don’t think it really did before, either. I’m treating that as out-of-scope for this PR (so we’re just focusing on the data here).

### CODE REVIEW

**Comment by Mr0grog** [comment]
The news page now looks like:

Screen Shot 2020-06-14 at 1 19 49 PM

**Comment by Mr0grog** [comment]
Update: sfbrigade/data-covid19-sfbayarea#81 has landed, so this PR should be good to go.

**Comment by kengoy** [comment]
@Mr0grog Some county news (especially Contra Costa) have too many contents so we may want to screen the latest 5 news in each county as next step. Thank you for your great work on this!

**Comment by Mr0grog** [comment]
> we may want to screen the latest 5 news in each county as next step.

@csaoma is on it! See sfbrigade/data-covid19-sfbayarea#43, where we’re adding functionality to limit results to a specified date range. 😄

**Comment by kengoy** [comment]
Awesome! :)

**Pull request merged**
