### PR TITLE
Feature/issue510

### PR DESCRIPTION
**Pull request by kengoy**
#510  Added hospitalization chart.

UI Wirefame:https://www.figma.com/file/iUS5LdAnuTKVei88QwPPCH/Bay-Area-Pandemic-Dashboard-(PanDa)-by-Bay-Area-Brigades

Screen Shot 2020-10-25 at 2 17 45 AM

### CODE REVIEW

**Comment by kengoy** [comment]
@nikobooth @benghancock  The front end is ready for the hospitalization chart https://deploy-preview-543--quizzical-jackson-a184d6.netlify.app you can review here. Please let me know if I am missing anything.

**Review by thuongho — APPROVED** [review]
LGTM.

**Review by nikobooth — APPROVED** [review]
I think this is great and ready to deploy, thanks for moving this one forward Kengo!

One nice-to-have would be to show the numbers for both occupied and available beds when you hover over either one, here's an example:
image
Something to easily see both bits of info for a given date when viewing this chart. This isn't something that should hold up deployment, however, if it's difficult to implement. I can make a feature request ticket to handle this later if that's a better path. Nice job!

**Comment by benghancock** [comment]
Looks really good! Thanks everyone for pulling this together. 

Just confirming: For the "COVID ICU Patients" stat, we are summing the `icu_covid_confirmed_patients` and `icu_suspected_covid_patients` values, correct?

**Comment by kengoy** [comment]
> Just confirming: For the "COVID ICU Patients" stat, we are summing the `icu_covid_confirmed_patients` and `icu_suspected_covid_patients` values, correct?

@benghancock I am showing only the # of `icu_covid_confirmed_patients` for the "COVID ICU Patients". Should I sum `icu_suspected_covid_patients` too? I can do that.

**Comment by kengoy** [comment]
@nikobooth I changed it to show the numbers for both occupied and available beds when you hover over either one. Could not follow the exact UI what you attached due to the provided function of chart library we use but still it works as you intended I believe.

You can check here: https://deploy-preview-543--quizzical-jackson-a184d6.netlify.app

**Comment by benghancock** [comment]
> @benghancock I am showing only the # of `icu_covid_confirmed_patients` for the "COVID ICU Patients". Should I sum `icu_suspected_covid_patients` too? Or should we separate the graphs?

I think that we should sum the confirmed and suspected patients, keeping them in the same graph. As I believe @nikobooth pointed out earlier, whether they are confirmed COVID cases or only suspected, they are still occupying ICU beds, so I think it makes sense to show the sum value in the chart.

**Comment by kengoy** [comment]
@benghancock Got it! Now confirmed and suspected patients are added in the charts "COVID ICU Patients".  https://deploy-preview-543--quizzical-jackson-a184d6.netlify.app

**Comment by benghancock** [comment]
Great! Looks good to go! Thanks again, @kengoy !

**Pull request merged**
