### PR TITLE
Feature/issue163

### PR DESCRIPTION
**Pull request by thuongho**
Sort sex chart so that it's descending order
Update and add Race Ethnicity chart per 1000
Ref #163

### CODE REVIEW

**Comment by kengoy** [comment]
@thuongho This is awesome job! It's interesting to see the new data charts of race/eth per 1,000. I thought depending on the less county population and less percentage of race ace/eth, the target population could be lower than 1,000 so the number shown in the chart per 1,000 may tend to become higher than other high race population percentage.  There is nothing to fix for this, but just speaking loud. cc @nikobooth

**Comment by kengoy** [comment]
@thuongho  Do you have any idea why the Latino/Hispanic chart is not shown in the 1,000 chart for San Mateo only? I understand "Unknown" is not shown as there is no population percentage data in the census.
Screen Shot 2020-09-27 at 3 27 06 PM

**Comment by kengoy** [comment]
> @thuongho Do you have any idea why the Latino/Hispanic chart is not shown in the 1,000 chart for San Mateo only? I understand "Unknown" is not shown as there is no population percentage data in the census.
> Screen Shot 2020-09-27 at 3 27 06 PM

I found there is no data for Latino/Hispanic in San Mateo. Is this because of the original data not including the data?
SAN_MATEO: {
     TOTAL: 411873,
     RACE: {
       WHITE: 0.585,
       AFRICAN_AMER: 0.026,
       NATIVE_AMER: 0.005,
       ASIAN: 0.197,
       PACIFIC_ISLANDER: 0.016,
       OTHER: 0.116,
       MULTIPLE_RACE: 0.054
     }
   },

**Comment by thuongho** [comment]
> @thuongho Do you have any idea why the Latino/Hispanic chart is not shown in the 1,000 chart for San Mateo only? I understand "Unknown" is not shown as there is no population percentage data in the census.
> Screen Shot 2020-09-27 at 3 27 06 PM


@kengoy that's odd. Yesterday when I was working on it the consensus didn't have latino population % for san mateo. I just searched now and the data is there! Let me update it

**Comment by thuongho** [comment]
@kengoy should be fixed now. Also, since the ethnic names from different counties are not standardized, I have some checks to catch it. It's definitely not a perfect solution though.

**Review by kengoy — APPROVED** [review]
Looks great 👍

**Comment by nikobooth** [comment]
@thuongho & @kengoy can we adjust the cases per 1000 so that they show in ranked order, highest measure at the top? Also removing unknown from that chart (I think you guys are already working on that one though).

**Pull request merged**
